/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kenzy
 */
public class updateinfo extends javax.swing.JFrame {

    /**
     * Creates new form updateinfo
     */
    public updateinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        id_textfield = new javax.swing.JTextField();
        Name_textfield = new javax.swing.JTextField();
        age_textfield = new javax.swing.JTextField();
        username_textfiled = new javax.swing.JTextField();
        PasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        search_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 352));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(id_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 170, 30));

        Name_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_textfieldActionPerformed(evt);
            }
        });
        jPanel1.add(Name_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, 30));
        jPanel1.add(age_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 170, 30));
        jPanel1.add(username_textfiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 170, 30));
        jPanel1.add(PasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 170, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        search_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        jPanel1.add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Update  Student Info");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 220, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        update_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Name_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_textfieldActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
            
         int id = Integer.parseInt(id_textfield.getText());
        //check first if the id textfield is empty or blank
       
            try {
                 Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
   String user = "coursesManagment";
     String pass = "root";
     String url = "jdbc:sqlserver://localhost:1433;databaseName=coursesManagmentSystem";
    Connection conn= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=coursesManagmentSystem",user,pass);

                
                String sqlquery = "SELECT name,age,User_name,Password FROM student WHERE ID=" + id + "";
                PreparedStatement pst = conn.prepareStatement(sqlquery);
                ResultSet rs = pst.executeQuery();
                //check if there is a result
                if (!rs.next()) {//if there is no result
                    JOptionPane.showMessageDialog(null, "no data found");
                } else {

//if there is a result
                    // id = Integer.parseInt(rs.getString(0));
                    String name = rs.getString(1);
                    int age = Integer.parseInt(rs.getString(2));
                    String username = rs.getString(3);
                    String password = rs.getString(4);

                    Name_textfield.setText(name);
                    age_textfield.setText(age + "");
                    username_textfiled.setText(username);
                    PasswordField1.setText(password);
        
                }    }
            catch (Exception ex){
             JOptionPane.showMessageDialog(null, ex);
            }



    }//GEN-LAST:event_search_btnActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
  // TODO add your handling code here:
        //check first if the id textfield is empty or blank
        ///////////////////////////////////////////////////////
        int id = Integer.parseInt(id_textfield.getText());
         String    name = Name_textfield.getText();
        int age = Integer.parseInt(age_textfield.getText());
        String username = username_textfiled.getText();
        String password = PasswordField1.getText();

                    try {
              Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
   String user = "coursesManagment";
     String pass = "root";
     String url = "jdbc:sqlserver://localhost:1433;databaseName=coursesManagmentSystem";
    Connection conn= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=coursesManagmentSystem",user,pass);
                     
                        String query2 = "UPDATE student SET  ID=" + id + ", name ='" + name + "', age =" + age + " ,User_name='" + username + "' ,Password ='" + password + "' WHERE ID=" + id + "";

                        PreparedStatement pst2 = conn.prepareStatement(query2);
                        pst2.executeUpdate();

                        Name_textfield.setText(name);
                        age_textfield.setText(age + "");
                        username_textfiled.setText(username);
                        PasswordField1.setText(password);
                        JOptionPane.showMessageDialog(null, "updated successfully");

                    } catch (Exception ex) {

                        JOptionPane.showMessageDialog(null, ex);
                    }

        
        
        
    }//GEN-LAST:event_update_btnActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateinfo.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateinfo.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateinfo.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateinfo.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name_textfield;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JTextField age_textfield;
    private javax.swing.JTextField id_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton search_btn;
    private javax.swing.JButton update_btn;
    private javax.swing.JTextField username_textfiled;
    // End of variables declaration//GEN-END:variables

}
